services:

  mongodb:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - './volumes/mongo/db:/data/db:z'
      - './volumes/mongo/configdb:/data/configdb:z'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      start_period: 10s
      start_interval: 1s
    networks:
      - default

  privmx-bridge:
    pre_start:
      - user: "0:0"
        command:
          - sh
          - -ec
          - |
            mkdir -p /work/privmx-bridge/storage/tmp
            mkdir -p /work/privmx-bridge/storage/files
            mkdir -p /work/privmx-bridge/plugins
            chown 1001:1001 \
              /work/privmx-bridge/storage \
              /work/privmx-bridge/storage/tmp \
              /work/privmx-bridge/storage/files \
              /work/privmx-bridge/plugins

    image: 'simplito/privmx-bridge:latest'
    env_file:
      - path: ./bridge.env
        required: false
    environment:
      PRIVMX_MONGO_URL: "mongodb://mongodb/"
      PRIVMX_CORS_ENABLED: "true"
    volumes:
      - './volumes/bridge/storage:/work/privmx-bridge/storage:z'
      - './volumes/bridge/plugins:/work/privmx-bridge/plugins:z'
    ports:
      - "9111:3000"
    depends_on:
      - mongodb
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          pmxbridge_up &&
          test -w /work/privmx-bridge/storage/tmp &&
          test -w /work/privmx-bridge/storage/files
      start_period: 20s
      start_interval: 1s
    networks:
      - default

networks:
  default:
    name: privmx-infra-network
    external: true
