services:

  mongodb:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - './volumes/mongo/db:/data/db'
      - './volumes/mongo/configdb:/data/configdb'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      start_period: 10s
      start_interval: 1s

  privmx-bridge:
    image: 'simplito/privmx-bridge'
    environment:
      PRIVMX_MONGO_URL: "mongodb://mongodb/"
      PRIVMX_CORS_ENABLED: "true"
    volumes:
      - './volumes/bridge/storage:/work/privmx-bridge/storage'
      - './volumes/bridge/plugins:/work/privmx-bridge/plugins'
    ports:
      - "9111:3000"
    depends_on:
      - mongodb
    healthcheck:
      test: pmxbridge_up
      start_period: 20s
      start_interval: 1s